version: 2

build:
  os: ubuntu-22.04
  apt_packages:
    - mono-complete
    - libmono-2.0-1
  
  tools:
    python: "3.13"

  commands:
    - pip install uv
    - pip install -U pythonnet
    - uv sync
    - uv run sphinx-build -b html docs/source $READTHEDOCS_OUTPUT/html

python:
  install:
    - method: pip
      path: .

sphinx:
   configuration: docs/source/conf.py


