version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"

  commands:
    - pip install uv
    - uv sync
    - uv run sphinx-build -b html docs/source $READTHEDOCS_OUTPUT/html

sphinx:
   configuration: docs/source/conf.py


