{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') %}
{% set describe_number = environ.get('GIT_DESCRIBE_NUMBER', '0') %}
{% set describe_hash = environ.get('GIT_DESCRIBE_HASH', 'untagged') %}
{% set py_version = environ['CONDA_PY'] %}

package:
  name: skzemax
  version: {{ version }}

source:
  git_url: ../

build:
  noarch: python
  number: {{ describe_number }}
  string: {{ describe_hash }}_{{ describe_number }}
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vvv

requirements:
  host:
    - python
    - pip
    - setuptools-scm
  run:
    - python
    - numpy
    - alive-progress
    - pythonnet

test:
  imports:
    - skZemax
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest tests

about:
  home: https://github.com/usask-arg/skZemax
  summary: A python API developed by the University of Saskatchewan Atmospheric Research Group to interface with Ansys Zemax OpticStudio. 
  license_file: ../LICENSE
